# Generated by Django 5.0.7 on 2024-07-25 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_img')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='apis.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_imgs')),
                ('starting_price', models.FloatField()),
                ('is_sold', models.BooleanField(default=False)),
                ('is_transferred', models.BooleanField(default=False)),
                ('current_bidder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_bids', to='apis.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.profile')),
            ],
        ),
    ]
