import type { Metadata } from 'next'
import Head from 'next/head'


import { Poppins } from "next/font/google"
 

import './globals.css'

 

 
// These styles apply to every route in the application
const fontSans = Poppins({
    subsets: ["latin"],
    weight: '400'
  })
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      <body className = {fontSans.className}>{children}</body>
    </html>
  )
}