GET http://127.0.0.1:8000/items/get_items_by_owner
Content-Type: application/json

{
    "username": "priyar"
}
###

POST http://127.0.0.1:8000/items/add_item
Content-Type: application/json
Authorization: Token 668c73099858a488e858cee1a661853836b7229e

{
    "name": "item1", 
    "description": "item1 description",
    "starting_price": 15.50

}
###
POST http://127.0.0.1:8000/user/logout 
Content-Type: application/json
Authorization: Token 668c73099858a488e858cee1a661853836b7229e

{
    "username": "priyar", 
    "password": "1234"
}